import type { MaterialAssetRef, MaterialSource } from '../types/config';

export type MaterialDefinitionSourceType = 'solid' | 'image' | 'upload' | 'generated';
export type MaterialMapType = 'thumbnail' | 'albedo' | 'bump' | 'normal' | 'roughness';

export interface MaterialDefinition {
  id: string;
  name: string;
  categoryId: string;
  sourceType: MaterialDefinitionSourceType;
  swatchColor: string;
  thumbnail: MaterialAssetRef | null;
  albedo: MaterialAssetRef | null;
  bump: MaterialAssetRef | null;
  normal: MaterialAssetRef | null;
  roughness: MaterialAssetRef | null;
  defaults: {
    width: number;
    height: number;
  };
  metadata?: {
    finish?: string;
    toneVariation?: number;
    featured?: boolean;
  };
  source: MaterialSource;
}

export interface MaterialCategory {
  id: string;
  displayName: string;
  icon: string;
  description: string;
}

function jpgAsset(path: string, size?: number): MaterialAssetRef {
  return {
    path,
    mimeType: 'image/jpeg',
    ...(size ? { width: size, height: size } : {}),
  };
}

function imageMaterial(options: {
  id: string;
  name: string;
  categoryId: string;
  swatchColor: string;
  thumbPath: string;
  albedoPath?: string;
  width: number;
  height: number;
  finish?: string;
  toneVariation?: number;
  featured?: boolean;
}): MaterialDefinition {
  const thumbnail = jpgAsset(options.thumbPath);
  const albedo = jpgAsset(options.albedoPath ?? options.thumbPath);
  const metadata =
    options.finish !== undefined || options.toneVariation !== undefined || options.featured !== undefined
      ? {
          ...(options.finish !== undefined ? { finish: options.finish } : {}),
          ...(options.toneVariation !== undefined ? { toneVariation: options.toneVariation } : {}),
          ...(options.featured !== undefined ? { featured: options.featured } : {}),
        }
      : null;

  return {
    id: options.id,
    name: options.name,
    categoryId: options.categoryId,
    sourceType: 'image',
    swatchColor: options.swatchColor,
    thumbnail,
    albedo,
    bump: null,
    normal: null,
    roughness: null,
    defaults: {
      width: options.width,
      height: options.height,
    },
    ...(metadata ? { metadata } : {}),
    source: {
      type: 'image',
      asset: albedo,
      fallbackColor: options.swatchColor,
    },
  };
}

/**
 * Material category definitions used by the Create editor.
 */
export const MATERIAL_CATEGORIES: MaterialCategory[] = [
  { id: 'organic', displayName: 'Organic', icon: '🍂', description: 'Natural organic materials' },
  { id: 'hybrid', displayName: 'Hybrid', icon: '🧬', description: 'Engineered hybrid materials' },
];

/**
 * Special material source types (not categories).
 */
export const SPECIAL_SOURCES = {
  SOLID_FILL: 'solid',
  UPLOAD: 'upload',
  GENERATED: 'generated',
} as const;

export const MATERIAL_LIBRARY: MaterialDefinition[] = [
  imageMaterial({
    id: 'organic-amara-ebony',
    name: 'AMARA EBONY',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/AMARA EBONY.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-anigrey-figured',
    name: 'ANIGREY FIGURED',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/ANIGREY FIGURED.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-afromosia',
    name: 'Afromosia',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Afromosia.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-anigre',
    name: 'Anigre',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Anigre.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-eucalyptus-2',
    name: 'EUCALYPTUS (2)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/EUCALYPTUS (2).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-eucalyptus',
    name: 'EUCALYPTUS',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/EUCALYPTUS.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-golden-cedar-2',
    name: 'GOLDEN CEDAR (2)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/GOLDEN CEDAR (2).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-lacewood',
    name: 'LACEWOOD',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/LACEWOOD.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-maccassar-ebony',
    name: 'MACCASSAR EBONY',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/MACCASSAR EBONY.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-mahogany-quarter',
    name: 'MAHOGANY QUARTER',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/MAHOGANY QUARTER.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-red-elm-crown-2',
    name: 'RED ELM CROWN (2)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/RED ELM CROWN (2).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-red-elm-crown',
    name: 'RED ELM Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/RED ELM Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-red-oak-quarter',
    name: 'RED OAK QUARTER',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/RED OAK QUARTER.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-rosewood-3',
    name: 'ROSEWOOD (3)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/ROSEWOOD (3).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-rosewood',
    name: 'ROSEWOOD',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/ROSEWOOD.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-red-cedar-quarter',
    name: 'Red Cedar Quarter',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Red Cedar Quarter.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-red-oak-crown',
    name: 'Red Oak Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Red Oak Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-santos-crown',
    name: 'SANTOS Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/SANTOS Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sapeli-crown',
    name: 'SAPELI CROWN',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/SAPELI CROWN.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sapeli-quarter',
    name: 'SAPELI QUARTER',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/SAPELI QUARTER.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-steam-beech',
    name: 'STEAM BEECH',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/STEAM BEECH.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sucupira-crown',
    name: 'SUCUPIRA Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/SUCUPIRA Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-santos',
    name: 'Santos',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Santos.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sapeli',
    name: 'Sapeli',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Sapeli.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sucupira',
    name: 'Sucupira',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Sucupira.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-sycamore',
    name: 'Sycamore',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Sycamore.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-teak-crown',
    name: 'Teak Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Teak Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-teak-quarter',
    name: 'Teak Quarter',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Teak Quarter.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-walnut-crown',
    name: 'WALNUT Crown',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/WALNUT Crown.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-walnut-quarter',
    name: 'WALNUT QUARTER',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/WALNUT QUARTER.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-white-oak-crown',
    name: 'WHITE OAK CROWN',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/WHITE OAK CROWN.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-white-oak-quarter',
    name: 'WHITE OAK quarter',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/WHITE OAK quarter.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-walnut-crown-2',
    name: 'Walnut Crown (2)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Walnut Crown (2).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-white-ash-crown',
    name: 'White ASH CROWN',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/White ASH CROWN.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-white-ash',
    name: 'White Ash',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/White Ash.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-zericote',
    name: 'ZERICOTE',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/ZERICOTE.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'organic-zericote-2',
    name: 'Zericote (2)',
    categoryId: 'organic',
    swatchColor: '#808080',
    thumbPath: '/materials/Organic/Zericote (2).jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-angora',
    name: 'ANGORA',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/ANGORA.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-almond-oak',
    name: 'Almond Oak',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Almond Oak.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-alpine',
    name: 'Alpine',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Alpine.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-arctic',
    name: 'Arctic',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Arctic.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-aurora',
    name: 'Aurora',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Aurora.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-biscotti',
    name: 'Biscotti',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Biscotti.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-cubist',
    name: 'CUBIST',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/CUBIST.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-capri',
    name: 'Capri',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Capri.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-charcoal',
    name: 'Charcoal',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Charcoal.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-chiffon-oak',
    name: 'Chiffon Oak',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Chiffon Oak.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-deck',
    name: 'DECK',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/DECK.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-desert-taupe',
    name: 'DESERT TAUPE',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/DESERT TAUPE.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-dove',
    name: 'Dove',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Dove.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-drift-wood',
    name: 'Drift wood',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Drift wood.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-dunes',
    name: 'Dunes',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Dunes.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-emerald-lagoon',
    name: 'Emerald Lagoon',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Emerald Lagoon.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-girgio-latte',
    name: 'Girgio Latte',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Girgio Latte.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-gothic-grey-grain',
    name: 'Gothic Grey Grain',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Gothic Grey Grain.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-grey-mist',
    name: 'Grey Mist',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Grey Mist.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-grey-velvet',
    name: 'Grey Velvet',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Grey Velvet.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-grunge',
    name: 'Grunge',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Grunge.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-heather',
    name: 'HEATHER',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/HEATHER.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-hazel',
    name: 'Hazel',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Hazel.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-hickory',
    name: 'Hickory',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Hickory.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-indigo-mirage',
    name: 'Indigo Mirage',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Indigo Mirage.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-interlace',
    name: 'Interlace',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Interlace.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-ivory-oak',
    name: 'Ivory Oak',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Ivory Oak.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-java',
    name: 'Java',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Java.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-kaleidoscope',
    name: 'Kaleidoscope',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Kaleidoscope.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-linen-oak',
    name: 'Linen Oak',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Linen Oak.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-lunar',
    name: 'Lunar',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Lunar.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-mochaccino',
    name: 'Mochaccino',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Mochaccino.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-moroccan-chevron',
    name: 'Moroccan Chevron',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Moroccan Chevron.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-mushroom',
    name: 'Mushroom',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Mushroom.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-mystic-ebony',
    name: 'Mystic Ebony',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Mystic Ebony.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-mystic-swirl',
    name: 'Mystic Swirl',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Mystic Swirl.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-noce-caramel',
    name: 'Noce Caramel',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Noce Caramel.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-noce-eternia',
    name: 'Noce Eternia',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Noce Eternia.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-noce-harmony',
    name: 'Noce Harmony',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Noce Harmony.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-ogee',
    name: 'Ogee',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Ogee.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-orchid',
    name: 'Orchid',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Orchid.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-oxford-grey',
    name: 'Oxford Grey',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Oxford Grey.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-phantom',
    name: 'PHANTOM',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/PHANTOM.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-piano',
    name: 'PIANO',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/PIANO.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-pine-bark',
    name: 'PINE BARK',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/PINE BARK.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-pinstripe',
    name: 'Pinstripe',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Pinstripe.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-pixel',
    name: 'Pixel',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Pixel.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-raven',
    name: 'Raven',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Raven.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-russet',
    name: 'Russet',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Russet.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
  imageMaterial({
    id: 'hybrid-rust',
    name: 'Rust',
    categoryId: 'hybrid',
    swatchColor: '#808080',
    thumbPath: '/materials/Hybrid/Rust.jpg',
    width: 400,
    height: 400,
    featured: false,
  }),
];

export function getMaterialCategory(id: string): MaterialCategory | undefined {
  return MATERIAL_CATEGORIES.find((category) => category.id === id);
}

export function getMaterialsByCategory(categoryId: string): MaterialDefinition[] {
  return MATERIAL_LIBRARY.filter((material) => material.categoryId === categoryId);
}

export function getMaterialById(id: string): MaterialDefinition | undefined {
  return MATERIAL_LIBRARY.find((material) => material.id === id);
}

export function getMaterialBySource(source: MaterialSource): MaterialDefinition | undefined {
  if (source.type === 'library') {
    return getMaterialById(source.assetId);
  }

  if (source.type !== 'image' && source.type !== 'generated') {
    return undefined;
  }

  const assetPath = source.asset?.path;
  if (!assetPath) return undefined;

  return MATERIAL_LIBRARY.find((material) => {
    return material.albedo?.path === assetPath || material.thumbnail?.path === assetPath;
  });
}
