import type { PatternCategory, PatternType, PatternConfig } from '../types/config';

export interface PatternDefinition {
  dimType?: 'single' | 'multi';
  type: PatternType;
  category: PatternCategory;
  rowColMode: 'grid' | 'module';
  rowMultiple: number;
  columnMultiple: number;
  displayName: string;
  widthLabel?: string;
  heightLabel?: string;
  description: string;
  previewPath: string;
  previewAssetPath?: string;
  defaults: {
    rows: number;
    columns: number;
    angle: number;
    stretchers: number;
    weaves: number;
  };
  parameterRanges: {
    rows: { min: number; max: number };
    columns: { min: number; max: number };
    angle: { min: number; max: number; step: number };
    stretchers?: { min: number; max: number };
    weaves?: { min: number; max: number };
  };
  defaultUnitWidth: number;
  defaultUnitHeight: number;
}

const ALL_PATTERN_CATALOG: PatternDefinition[] = [
  {
    type: 'none',
    dimType: 'multi',
    category: 'random',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'None',
    description: 'Single material field without a repeated layout',
    previewPath: '',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 1 },
      columns: { min: 1, max: 1 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 1200,
    defaultUnitHeight: 1200,
  },
  {
    type: 'running_bond',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 2,
    displayName: 'Common',
    description: 'Common bond with header courses repeating every few rows',
    previewPath: 'M0,8h40M0,24h40M0,0h10v16H0M10,0h20v16M30,0h10v16 M0,16h20v16M20,16h20v16',
    previewAssetPath: 'patterns/running_bond.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 3, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
      stretchers: { min: 1, max: 6 },
    },
    defaultUnitWidth: 400,
    defaultUnitHeight: 100,
  },
  {
    type: 'stack_bond',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'grid',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Stack',
    description: 'Bricks stacked directly on top of each other',
    previewPath: 'M0,0h40M0,16h40M0,32h40M0,0v32M10,0v32M20,0v32M30,0v32M40,0v32',
    previewAssetPath: 'patterns/stack_bond.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 215,
    defaultUnitHeight: 65,
  },
  {
    type: 'stretcher_bond',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'grid',
    rowMultiple: 2,
    columnMultiple: 1,
    displayName: 'Stretcher',
    description: 'All stretchers with fixed half-offset courses',
    previewPath: 'M0,0h20v12H0zM20,0h20v12M0,12h10v12M10,12h20v12M30,12h10v12',
    previewAssetPath: 'patterns/stretcher_bond.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 215,
    defaultUnitHeight: 65,
  },
  {
    type: 'flemish_bond',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 2,
    displayName: 'Flemish',
    description: 'Alternating stretchers and headers in each course',
    previewPath: 'M0,0h12v10H0M12,0h20v10M32,0h8v10M0,10h8v10M8,10h20v10M28,10h12v10',
    previewAssetPath: 'patterns/flemish_bond.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 215,
    defaultUnitHeight: 65,
  },
  {
    type: 'herringbone',
    dimType: 'multi',
    category: 'paving',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 2,
    displayName: 'Herringbone',
    description: 'V-shaped zigzag pattern at 45°',
    previewPath: 'M0,20h20v20H0M20,0h20v20z',
    previewAssetPath: 'patterns/herringbone.svg',
    defaults: { rows: 8, columns: 8, angle: 45, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 50 },
      columns: { min: 2, max: 50 },
      angle: { min: 45, max: 45, step: 1 },
    },
    defaultUnitWidth: 200,
    defaultUnitHeight: 100,
  },
  {
    type: 'chevron',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'grid',
    rowMultiple: 1,
    columnMultiple: 2,
    displayName: 'Chevron',
    description: 'V-shaped pattern with angled cuts',
    previewPath: 'M0,20 L20,0 L20,10 L0,30z M20,0 L40,20 L40,30 L20,10z',
    previewAssetPath: 'patterns/chevron.svg',
    defaults: { rows: 6, columns: 4, angle: 30, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 50 },
      columns: { min: 2, max: 50 },
      angle: { min: 0, max: 70, step: 1 },
    },
    defaultUnitWidth: 400,
    defaultUnitHeight: 100,
  },
  {
    type: 'staggered',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Staggered',
    description: 'Staggered masonry layout',
    previewPath: '',
    previewAssetPath: 'patterns/staggered.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 215,
    defaultUnitHeight: 65,
  },
  {
    type: 'ashlar',
    dimType: 'multi',
    category: 'paving',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Ashlar',
    description: 'Cut stone with varying sizes in a coursed pattern',
    previewPath: 'M0,0h25v14H0M25,0h15v14M0,14h15v14M15,14h25v14',
    previewAssetPath: 'patterns/ashlar.svg',
    defaults: { rows: 4, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 30 },
      columns: { min: 1, max: 30 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 400,
    defaultUnitHeight: 400,
  },
  {
    type: 'cubic',
    dimType: 'single',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 3,
    displayName: 'Cubic',
    description: 'Isometric cube illusion using interlocking rhombus tiles',
    previewPath: '',
    previewAssetPath: 'patterns/cubic.svg',
    defaults: { rows: 6, columns: 6, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 30 },
      columns: { min: 2, max: 30 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 180,
    defaultUnitHeight: 180,
  },
  {
    type: 'hexagonal',
    dimType: 'single',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 1,
    displayName: 'Hexagonal',
    widthLabel: 'Size',
    description: 'Honeycomb hexagonal tile pattern',
    previewPath: 'M20,2 L36,12 L36,28 L20,38 L4,28 L4,12z',
    previewAssetPath: 'patterns/hexagonal.svg',
    defaults: { rows: 6, columns: 6, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 30 },
      columns: { min: 2, max: 30 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 150,
    defaultUnitHeight: 150,
  },
  {
    type: 'basketweave',
    dimType: 'single',
    category: 'paving',
    rowColMode: 'module',
    rowMultiple: 6,
    columnMultiple: 6,
    displayName: 'Basketweave',
    description: 'Pairs of bricks alternating horizontal/vertical',
    previewPath: 'M0,0h20v8H0M0,8h8v20M8,28h20v8M28,8h8v20',
    previewAssetPath: 'patterns/basketweave.svg',
    defaults: { rows: 6, columns: 6, angle: 0, stretchers: 1, weaves: 3 },
    parameterRanges: {
      rows: { min: 2, max: 50 },
      columns: { min: 2, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
      weaves: { min: 2, max: 10 },
    },
    defaultUnitWidth: 200,
    defaultUnitHeight: 100,
  },
  {
    type: 'hopscotch',
    dimType: 'multi',
    category: 'paving',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 2,
    displayName: 'Hopscotch',
    description: 'Mixed-size paving in hopscotch arrangement',
    previewPath: '',
    previewAssetPath: 'patterns/hopscotch.svg',
    defaults: { rows: 4, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 20 },
      columns: { min: 2, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 300,
    defaultUnitHeight: 300,
  },
  {
    type: 'diamond',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 1,
    displayName: 'Diamond',
    description: 'Diamond shape lattice',
    previewPath: '',
    previewAssetPath: 'patterns/diamond.svg',
    defaults: { rows: 6, columns: 6, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 30 },
      columns: { min: 2, max: 30 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 180,
    defaultUnitHeight: 180,
  },
  {
    type: 'intersecting_circle',
    dimType: 'single',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 1,
    displayName: 'Circular',
    description: 'Circle lattice with overlapping arcs',
    previewPath: '',
    previewAssetPath: 'patterns/intersecting_circle.svg',
    defaults: { rows: 6, columns: 6, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 30 },
      columns: { min: 2, max: 30 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 180,
    defaultUnitHeight: 180,
  },
  {
    type: 'fishscale',
    dimType: 'single',
    category: 'roofing',
    rowColMode: 'module',
    rowMultiple: 2,
    columnMultiple: 1,
    displayName: 'Fishscale',
    widthLabel: 'Diameter',
    description: 'Scaled shingle pattern with rounded edges',
    previewPath: '',
    previewAssetPath: 'patterns/fishscale.svg',
    defaults: { rows: 8, columns: 6, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 2, max: 40 },
      columns: { min: 2, max: 40 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 400,
    defaultUnitHeight: 400,
  },
  {
    type: 'french',
    dimType: 'multi',
    category: 'brick_bond',
    rowColMode: 'module',
    rowMultiple: 3,
    columnMultiple: 3,
    displayName: 'French',
    description: 'French bond style masonry layout',
    previewPath: '',
    previewAssetPath: 'patterns/french.svg',
    defaults: { rows: 6, columns: 4, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 50 },
      columns: { min: 1, max: 50 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 215,
    defaultUnitHeight: 65,
  },
  {
    type: 'venzowood',
    dimType: 'single',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Venzowood',
    widthLabel: 'Module Size',
    description: 'Decorative diamond parquet module with long inlay strips',
    previewPath: '',
    previewAssetPath: 'patterns/venzowood.svg',
    defaults: { rows: 3, columns: 3, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 45, step: 1 },
    },
    defaultUnitWidth: 860,
    defaultUnitHeight: 860,
  },
  {
    type: 'venzowood_2',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Venzowood 2',
    widthLabel: 'Module Size',
    description: 'Decorative mixed-size rounded rectangular wood module',
    previewPath: '',
    previewAssetPath: 'patterns/venzowood_2.svg',
    defaults: { rows: 2, columns: 2, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 860,
    defaultUnitHeight: 860,
  },
  {
    type: 'venzowood_3',
    dimType: 'single',
    category: 'organic',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Venzowood 3',
    widthLabel: 'Module Size',
    description: 'Organic freeform wood and stone module',
    previewPath: '',
    previewAssetPath: 'patterns/venzowood_3.svg',
    defaults: { rows: 2, columns: 2, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 860,
    defaultUnitHeight: 860,
  },
  {
    type: 'chequer_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Chequer Pattern',
    description: 'Four-panel chequer module with elongated rectangular blocks',
    previewPath: '',
    previewAssetPath: 'patterns/chequer_pattern.svg',
    defaults: { rows: 2, columns: 2, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 200,
    defaultUnitHeight: 400,
  },
  {
    type: 'concave_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Concave Pattern',
    description: 'Slim vertical slat module with concave channel spacing',
    previewPath: '',
    previewAssetPath: 'patterns/concave_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 118.11,
    defaultUnitHeight: 1968.5,
  },
  {
    type: 'convex_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Convex Pattern',
    description: 'Wide vertical slat module with convex channel spacing',
    previewPath: '',
    previewAssetPath: 'patterns/convex_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 196.85,
    defaultUnitHeight: 1968.5,
  },
  {
    type: 'grate_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Grate Pattern',
    description: 'Decorative grate module with flowing routed linework',
    previewPath: '',
    previewAssetPath: 'patterns/grate_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 2000,
    defaultUnitHeight: 2000,
  },
  {
    type: 'rhombus_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Rhombus Pattern',
    description: 'Layered rhombus motif with central diamond detailing',
    previewPath: '',
    previewAssetPath: 'patterns/rhombus_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 417.83,
    defaultUnitHeight: 417.83,
  },
  {
    type: 'ripple_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Ripple Pattern',
    description: 'Fine vertical ripple module with repeated narrow grooves',
    previewPath: '',
    previewAssetPath: 'patterns/ripple_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 39.37,
    defaultUnitHeight: 2000,
  },
  {
    type: 'weave_pattern',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Weave Pattern',
    description: 'Rounded vertical weave module with alternating strap rhythm',
    previewPath: '',
    previewAssetPath: 'patterns/weave_pattern.svg',
    defaults: { rows: 1, columns: 1, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 60.06,
    defaultUnitHeight: 330.32,
  },
  {
    type: 'venzowood_4',
    dimType: 'multi',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Venzowood 4',
    widthLabel: 'Panel Width',
    heightLabel: 'Panel Height',
    description: 'Tall decorative wood panel module with circular inlays',
    previewPath: '',
    previewAssetPath: 'patterns/venzowood_4.svg',
    defaults: { rows: 2, columns: 2, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 350,
    defaultUnitHeight: 980,
  },
  {
    type: 'venzowood_5',
    dimType: 'single',
    category: 'geometric',
    rowColMode: 'module',
    rowMultiple: 1,
    columnMultiple: 1,
    displayName: 'Venzowood 5',
    widthLabel: 'Module Size',
    description: 'Decorative floral and star wood inlay module',
    previewPath: '',
    previewAssetPath: 'patterns/venzowood_5.svg',
    defaults: { rows: 2, columns: 2, angle: 0, stretchers: 1, weaves: 1 },
    parameterRanges: {
      rows: { min: 1, max: 20 },
      columns: { min: 1, max: 20 },
      angle: { min: 0, max: 0, step: 1 },
    },
    defaultUnitWidth: 860,
    defaultUnitHeight: 860,
  },
];

export const PATTERN_CATALOG: PatternDefinition[] = ALL_PATTERN_CATALOG.filter(
  (pattern) => pattern.type !== 'none',
);

/**
 * Get all patterns for a specific category.
 */
export function getPatternsByCategory(category: PatternCategory): PatternDefinition[] {
  return PATTERN_CATALOG.filter((p) => p.category === category);
}

/**
 * Get a pattern definition by its type.
 */
export function getPatternByType(type: PatternType): PatternDefinition | undefined {
  return ALL_PATTERN_CATALOG.find((p) => p.type === type);
}

/**
 * Get default pattern config for a given pattern type.
 */
export function getDefaultPatternConfig(type: PatternType): PatternConfig | undefined {
  const def = getPatternByType(type);
  if (!def) return undefined;
  return {
    type: def.type,
    category: def.category,
    orientation: 'horizontal',
    ...def.defaults,
    rows: 1,
    columns: 1,
  };
}

/**
 * All available pattern categories with display names.
 */
export const PATTERN_CATEGORIES: { id: PatternCategory; displayName: string }[] = [
  { id: 'brick_bond', displayName: 'Brick Bond' },
  { id: 'paving', displayName: 'Paving' },
  { id: 'geometric', displayName: 'Geometric' },
  { id: 'organic', displayName: 'Organic' },
  { id: 'roofing', displayName: 'Roofing' },
];
